CREATE SCHEMA IF NOT EXISTS ARTICLES;

CREATE TABLE IF NOT EXISTS ARTICLES.RAW_ENTITIES (
  key  VARCHAR(16)   NOT NULL PRIMARY KEY,
  url  VARCHAR(256)  NOT NULL,
  title VARCHAR(256) NOT NULL,
  published_date VARCHAR(256) NOT NULL,
  description VARCHAR(512),
  author VARCHAR(32) NOT NULL
);